---
- name: Install release vector
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Setup metal-stack release vector
      metal_stack_release_vector:
        vectors:
          - url: oci://ghcr.io/metal-stack/releases:{{ metal_stack_release_version }}
            meta_var: metal_stack_release
            from_role_defaults:
              - metal-roles/common/roles/defaults
