name: metal-deployment image from master

on:
  push:
    branches:
      - master
    paths:
    - 'metal-deployment/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v1
      id: tagName
    - name: Build the Docker images
      run: |
        cd metal-deployment/base
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make dockerimage
        make dockerpush
    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
