name: metal-deployment image from release tag

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build the Docker images
      run: |
        cd metal-deployment/base
        export GITHUB_TAG_NAME=pr-${GITHUB_REF##*/}
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make dockerimage
        make dockerpush
